[build]
compiler = "gcc"

[[targets]]
name = "test"
src = "./src"
include_dir = "./include"
type = "exe"
cflags = "-Werror -Wall"
libs = ""

[[targets]]
name = "noop"
src = "./src"
include_dir = "./include"
type = "dll"
cflags = "-Werror -Wall"
libs = ""
